def get_non_ingredients(all_ingredients):
    non_ingredients = set(
        [i for i in all_ingredients if i.endswith("ed") and "_" not in i]
    ) - {"aniseed", "flaxseed", "seaweed"}
    non_ingredients |= {
        "instant",
        "clove",
        "plus",
        "leaves",
        "bottle",
        "white",
        "extract",
        "extra",
        "yellow",
        "green",
        "black",
        "dry",
        "more",
        "a",
        "topping",
        "half",
        "other",
        "mix",
        "chunky",
        "any",
        "blend",
        "purple",
        "raw",
        "essence",
        "american",
        "organic",
        "natural",
        "soft",
        "quick",
        "smooth",
        "blue",
        "fresh",
        "whole",
        "swiss",
        "wild",
        "clean",
        "base",
        "indian",
        "iceberg",
        "flavors",
        "cones",
        "rich",
        "s",
        "st",
        "m",
        "blood",
    }
    return non_ingredients
